name: Gradle Tests on Feature Branches

on:
  push:
    branches:
      - "feat/**"

jobs:
  tests:
    name: Gradle Tests (TDD Mode)
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Give permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests (TDD Mode)
        run: ./gradlew test
        continue-on-error: true